---
- name: yum_install
  yum: pkg={{ item }} state=installed update_cache=yes
  when: pkg_list is defined and ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  with_items: pkg_list
  tags:
     - yum
