#ansible-playbook main.yml --tags="base-roles" -vvv
---
- hosts: TestCentos
  remote_user: ansible
  gather_facts: yes
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - vars/users.yml
#    - "{{ private_dir }}/p.yml"
  roles:
#    - { role: ansible-role-ntp }
#    - { role: ansible-sysctl, tags: ['sysctl'] }
#    - { role: ansible-motd }
#    - { role: ansible-motd }
#    - { role: ansible-apt, pkg_list: ['git'] }
#    - { role: ansible-yum, pkg_list: ['sysstat'] }
#    - { role: cron, tags: ['backups_to_s3_cron'] }
#    - { role: ansible-users }
  tasks:
   - debug: msg="reading from  {{ env_name }}"

