#ansible-playbook main.yml --tags="base-roles" -vvv
---
- hosts: TestCentos
  remote_user: ansible
  gather_facts: yes
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - vars/users.yml
#    - "{{ private_dir }}/p.yml"
  roles:
    - { role: ansible-role-ntp }
    - { role: ansible-sysctl, tags: ['sysctl'] }
